AlNotifi/urls.py
from django.urls import path, include
from .views import *

from rest_framework.routers import DefaultRouter

from django.conf import settings
from django.conf.urls.static import static


from .views import customhandler404

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('test/', test_view, name='test'),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView, name='logout'),
    path('profile/<int:id>/', ProfileView.as_view(), name='profile'),
    path('profile/update/', ProfileUpdateView.as_view(), name='profile_update'),
    path('all_notifications/', NotificationsListView.as_view(), name="all_notifications"),
    path('oauth2/discord/login/', discord_login, name='discord_oauth_login'),
    path('oauth2/discord/redirect/', discord_login_redirect, name='discord_oauth_redirect'),
    path('ouath2/discord/unlink/', discord_unlink, name='discord_unlink'),
    path('api/create_notification/', NotificationsCreateView.as_view(), name='create_notification'),
    path('api/delete_notification/<int:id>/', NotificationsDeleteView.as_view(), name='delete_notification'),
    path('api/update_notification/<int:id>/', NotificationsUpdateView.as_view(), name='update_notification'),
    path('api/list_notifications/', NotificationsListApiView.as_view(), name='list_notifications'),
]
handler404 = customhandler404
handler403 = customhandler403

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Notifications/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AlNotifi.urls')),
]

AlNotifi/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import timedelta


class DiscordProfile(models.Model):
    discord_id = models.BigIntegerField(null=True)
    discord_tag = models.CharField(max_length=100)
    avatar = models.CharField(max_length=100, null=True)
    public_flags = models.IntegerField()
    flags = models.IntegerField()
    global_name = models.CharField(max_length=100, null=True)
    locale = models.CharField(max_length=100)
    mfa_enabled = models.BooleanField()
    last_login = models.DateTimeField()


class Notifications(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    message = models.TextField(max_length=500)
    time = models.DateTimeField()
    # SENT_CHOICES = (
    #     ('discord', 'Discord'),
    #     ('telegram', 'Telegram'),
    #     ('phone', 'Phone'),
    #     ('email', 'Email'),
    # )
    # sent_to = models.CharField(max_length=10, choices=SENT_CHOICES)
    is_sent = models.BooleanField(default=False)
    task_id = models.CharField(max_length=100, blank=True, null=True)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    discord_profile = models.OneToOneField(DiscordProfile, on_delete=models.SET_NULL, blank=True, null=True)
    bio = models.TextField(max_length=250, blank=True)
    phone = models.BigIntegerField(blank=True, null=True)
    full_name = models.CharField(blank=True, null=True)
    address = models.CharField(blank=True, null=True)

    profile_picture = models.ImageField(upload_to='profile_pics/', blank=True, null=True)

    def __str__(self):
        return self.user.username

AlNotifi/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import UserProfile, Notifications

class LoginForm(forms.Form):
    username = forms.CharField(max_length=65)
    password = forms.CharField(widget=forms.PasswordInput)

class UserCreateForm(UserCreationForm):

    email = forms.EmailField()
    bio = forms.CharField(max_length=500)
    profile_picture = forms.ImageField(required=False)
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for fieldname in ['password2', 'username']:
            self.fields[fieldname].help_text = None

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("This email is already in use.")
        return email
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'bio', 'profile_picture']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['bio', 'profile_picture', 'phone', 'full_name', 'address']

templates/CRUD_notifi.html
{% extends 'base.html' %}

{% block head %}
    {% load static %}
    <script src={% static 'js/CRUD.js' %}></script>
{% endblock %}

{% block content %}

{% if notifications %}
<div class="container mt-5">
    <h2>Update Notification</h2>
    <form id="NotificationForm" action="{% url 'CRUD_notification' id=notification_id %}" method="PUT">
      {% csrf_token %}
      <div class="form-group">
        <label for="title">Title:</label>
        <input type="text" class="form-control" id="title" name="title" value="{{ notifications.title }}" required>
      </div>
      <div class="form-group">
        <label for="message">Message:</label>
        <textarea class="form-control" id="message" name="message" required>{{ notifications.message }}</textarea>
      </div>
      <div class="form-group">
        <label for="time">Time:</label>
        <input type="datetime-local" class="form-control" id="time" name="time" value="{{ notifications.time }}" required>
      </div>
      <button type="submit" class="btn btn-primary">Update Notification</button>
    </form>
  </div>
{% else %}
    <p>No notifications available.</p>
    <a class="btn btn-primary" href="{% url 'create_notification' %}">Add Notification</a>
{% endif %}
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
<head>

    {% load static %}
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>None</title>
    {% endif %}
    {% if style %}
        <link rel="stylesheet" href="{% static 'css/style_'|add:style|add:'.css' %}">
    {% endif %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="{% static 'css/style_base.css' %}">

    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link href="//fonts.googleapis.com/css?family=Roboto:400,700&display=swap" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://kit.fontawesome.com/bf1861485d.js" crossorigin="anonymous"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>

    {% block head %}
    {% endblock %}
</head>
<body>
<header>
<nav class="navbar navbar-icon-top navbar-expand-lg navbar-dark navbar-transparent">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li {% if request.resolver_match.view_name == 'index' %} class="active" {% endif %}>
                <a class="nav-link" href="{% url 'index' %}">
                    <span class="fa-solid fa-home"></span>
                    <span class="badge badger-danger">Home</span>
                </a>
            </li>
            {% if user.is_authenticated is False %}
                <li {% if request.resolver_match.view_name == 'register' %} class="active" {% endif %}>
                    <a class="nav-link" href="{% url 'register' %}">
                        <i class="fa-solid fa-arrow-right-to-bracket"></i>
                        <span class="badge badger-danger">Sign Up</span>
                    </a>
                </li>
                <li {% if request.resolver_match.view_name == 'login' %} class="active" {% endif %}>
                    <a class="nav-link" href="{% url 'login' %}">
                        <i class="fa-solid fa-arrow-right-to-bracket"></i>
                        <span class="badge badger-danger">Log in</span>
                    </a>
                </li>
            {% endif %}
            {% if user.is_authenticated %}
                <li {% if request.resolver_match.view_name == 'profile' %} class="active" {% endif %}>
                    <a class="nav-link" href="{% url 'profile' id=user.id%}">
                        <i class="fa-solid fa-user"></i>
                        <span class="badge badger-danger">Profile</span>
                    </a>
                </li>
                <li {% if request.resolver_match.view_name == 'all_notifications' %} class="active" {% endif %}>
                    <a class="nav-link" href="{% url 'all_notifications' %}">
                        <i class="fa-solid fa-list"></i>
                        <span class="badge badger-danger">Tasks</span>
                    </a>
                </li>
                <li {% if request.resolver_match.view_name == 'create_notification' %} class="active" {% endif %}>
                    <a class="nav-link" href="{% url 'create_notification' %}">
                        <i class="fa-solid fa-add"></i>
                        <span class="badge badger-danger">Add Notification</span>
                    </a>
                </li>
                <li>
                    <a class="nav-link" href="https://discord.gg/uUy44K6VT5">
                        <i class="fa-brands fa-discord"></i>
                        <span class="badge badger-danger">Discord guild</span>
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa-solid fa-user"></i>
                        <span class="badge badger-danger">{{ request.user.username }}</span>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if request.user.is_authenticated %}
                            <a class="dropdown-item" href="{% url 'discord_oauth_login' %}">Link discord</a>
                        {% endif %}
                        <a class="dropdown-item" href="{% url 'profile_update' %}">Edit profile</a>
                    </div>
                </li>
            {% endif %}
        </ul>

        <ul class="navbar-nav ">
            {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'logout' %}">
                    <i class="fa-solid fa-arrow-right-from-bracket"></i>
                    <span class="badge badger-danger">Logout</span>
                </a>
            {% endif %}
        </ul>
    </div>
</nav>
</header>
<main>
<div class="container">
    {% block content %}
    {% endblock %}
</div>
</main>

<footer class="footer">
    <div class="container">
        <p>&copy; 2024 Allah Notifications</p>
        <div class="social-icons">
            <a href="https://azov.org.ua/" class="fa-solid" target="_blank">Azov</a>
            <a href="https://t.me/s/ssternenko" class="fa-solid" target="_blank">Pan Sternenko</a>
            <a href="https://bank.gov.ua/ua/about/support-the-armed-forces" class="fa-solid" target="_blank">support</a>
        </div>
    </div>
</footer>
</body>
{% block extrascripts %}
{% endblock %}
</html>

</body>
</html>

templates/base_old.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>None</title>
    {% endif %}
    {% if style %}
        <link rel="stylesheet" href="{% static 'css/style_'|add:style|add:'.css' %}">
    {% endif %}
    <link rel="stylesheet" href="{% static 'css/style_base_old.css'%}">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link href="//fonts.googleapis.com/css?family=Roboto:400,700&display=swap" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://kit.fontawesome.com/bf1861485d.js" crossorigin="anonymous"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    {% block head %}
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-icon-top navbar-expand-lg navbar-dark bg-dark navbar-transparent">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li {% if request.resolver_match.view_name == 'index' %} class="active" {% endif %}>
                <a class="nav-link" href="{% url 'index' %}">
                    <span class="fa-solid fa-home"></span>
                    <span class="badge badger-danger">Home</span>
                </a>
            </li>
            {% if user.is_authenticated is False %}
                <li {% if request.resolver_match.view_name == 'register' %} class="active" {% endif %}>
                    <a class="nav-link" href="{% url 'register' %}">
                        <i class="fa-solid fa-arrow-right-to-bracket"></i>
                        <span class="badge badger-danger">Sign Up</span>
                    </a>
                </li>
                <li {% if request.resolver_match.view_name == 'login' %} class="active" {% endif %}>
                    <a class="nav-link" href="{% url 'login' %}">
                        <i class="fa-solid fa-arrow-right-to-bracket"></i>
                        <span class="badge badger-danger">Log in</span>
                    </a>
                </li>
            {% endif %}
            {% if user.is_authenticated %}
                <li {% if request.resolver_match.view_name == 'profile' %} class="active" {% endif %}>
                    <a class="nav-link" href="{% url 'profile' id=user.id%}">
                        <i class="fa-solid fa-user"></i>
                        <span class="badge badger-danger">Profile</span>
                    </a>
                </li>
                <li {% if request.resolver_match.view_name == 'Add task' %} class="active" {% endif %}>
                    <a class="nav-link" href="{% url 'all_notifications' %}">
                        <i class="fa-solid fa-list"></i>
                        <span class="badge badger-danger">Tasks</span>
                    </a>
                </li>
                <li {% if request.resolver_match.view_name == 'Add task' %} class="active" {% endif %}>
                    <a class="nav-link" href="{% url 'create_notification' %}">
                        <i class="fa-solid fa-add"></i>
                        <span class="badge badger-danger">Add Notification</span>
                    </a>
                </li>
                <li>
                    <a class="nav-link" href="https://discord.gg/uUy44K6VT5">
                        <i class="fa-brands fa-discord"></i>
                        <span class="badge badger-danger">Discord guild</span>
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa-solid fa-user"></i>
                        <span class="badge badger-danger">{{ request.user.username }}</span>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if request.user.is_authenticated %}
                            <a class="dropdown-item" href="{% url 'discord_oauth_login' %}">Link discord</a>
                        {% endif %}
                        <a class="dropdown-item" href="{% url 'profile_update' %}">Edit profile</a>
                    </div>
                </li>
            {% endif %}
        </ul>

        <ul class="navbar-nav ">
            {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'logout' %}">
                    <i class="fa-solid fa-arrow-right-from-bracket"></i>
                    <span class="badge badger-danger">Logout</span>
                </a>
            {% endif %}
        </ul>
    </div>
</nav>
<div class="container">
    {% block content %}
    {% endblock %}
</div>

<footer class="footer">
    <div class="container">
        <p>&copy; 2024 Allah Notifications</p>
        <div class="social-icons">
            <a href="https://azov.org.ua/" class="fa-solid" target="_blank">Azov</a>
            <a href="https://t.me/s/ssternenko" class="fa-solid" target="_blank">Pan Sternenko</a>
            <a href="https://bank.gov.ua/ua/about/support-the-armed-forces" class="fa-solid" target="_blank">support</a>
        </div>
    </div>
</footer>
</body>
{% block extrascripts %}
{% endblock %}
</html>

templates/create_notifi.html
{% extends 'base.html' %}

{% block content %}
  {% load static %}
    <div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto custom-card">
            <div class="card">
                <div class="card-body">
                <form id="NotificationForm" action="{% url 'create_notification' %}" method="post" enctype="application/json">
                        {% csrf_token %}
                        <h1>Create Notification</h1>
                        <hr>
                        <div class="form-group">
                            <label for="title">Title:</label>
                            <input type="text" class="form-control" id="title" name="title" required>
                        </div>
                        <div class="form-group">
                            <label for="message">Message:</label>
                            <textarea class="form-control" id="message" name="message" required></textarea>
                        </div>
                        <div class="form-group">
                            <label for="time">Time:</label>
                            <input type="datetime-local" class="form-control" id="time" name="time" required>
                        </div>
                        <p>To receive the notification, you must be on the <a href="https://discord.gg/uUy44K6VT5"}>discord guild</a></p>
                        <button type="submit" class="btn btn-primary">Create</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/create_profile.html
{% block content %}
    {% if request.user.is_authenticated %}
        <div class="header-bar">
            <a href="#">Back</a>
        </div>
    <div class="card-body">
        <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <input class="button" type="submit" value="Submit">
        </form>
    </div>
{% else %}
    <a>href="{% url 'login' %}"Login;</a>
{% endif %}

{% endblock content %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
    <!-- Контент страницы -->
    <div class="container">
        <div class="row">
            <div class="col-md-8">
            </div>
        </div>
    </div>
{% endblock %}

templates/list_notifi.html
{% extends 'base.html' %}
{% block head %}
{% endblock %}
{% block content %}
    {% load static %}
    <title>Notifi list</title>
    <script src={% static 'js/list_notifi.js' %}></script>
    <link rel="stylesheet" href="{% static 'css/style_list_notifi.css' %}">
    <div class="container mt-5">
        <div class="card">
            <div class="card-body">
                <h1 class="card-title">Notifications</h1>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Title</th>
                                <th>Message</th>
                                <th>Time</th>
                                <th>Is Sent</th>
                            </tr>
                        </thead>
                        <tbody id="notifications-table-body">
                            <!-- Notifications will be dynamically added here -->
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="confirmation-modal" tabindex="-1" role="dialog" aria-labelledby="confirmation-modal-label" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="confirmation-modal-label">Confirm Deletion</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Do you sure, that you want to delete this notification?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-danger" id="confirm-delete">Delete</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/profile_update.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto custom-card">
            <div class="card">
                <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <h1>Update profile</h1>
                        <hr>
                        <div class="form-group">
                            <label for="id_bio">Bio:</label>
                            <textarea class="form-control {% if form.bio.errors %} is-invalid {% endif %}" id="id_bio" name="bio">{{ form.bio.value }}</textarea>
                            {% for error in form.bio.errors %}
                                <div class="invalid-feedback">{{ error }}</div>
                            {% endfor %}
                        </div>
                        <div class="form-group">
                            <label for="id_profile_picture">Profile Picture:</label>
                            <input type="file" class="form-control-file {% if form.profile_picture.errors %} is-invalid {% endif %}" id="id_profile_picture" name="profile_picture">
                            {% for error in form.profile_picture.errors %}
                                <div class="invalid-feedback">{{ error }}</div>
                            {% endfor %}
                        </div>
                        <div class="form-group">
                            <label for="id_phone">Phone:</label>
                            <input type="text" class="form-control {% if form.phone.errors %} is-invalid {% endif %}" id="id_phone" name="phone">
                            {% for error in form.phone.errors %}
                                <div class="invalid-feedback">{{ error }}</div>
                            {% endfor %}
                        </div>
                        <div class="form-group">
                            <label for="id_full_name">Full Name:</label>
                            <input type="text" class="form-control {% if form.full_name.errors %} is-invalid {% endif %}" id="id_full_name" name="full_name">
                            {% for error in form.full_name.errors %}
                                <div class="invalid-feedback">{{ error }}</div>
                            {% endfor %}
                        </div>
                        <div class="form-group">
                            <label for="id_address">Address:</label>
                            <input type="text" class="form-control {% if form.address.errors %} is-invalid {% endif %}" id="id_address" name="address">
                            {% for error in form.address.errors %}
                                <div class="invalid-feedback">{{ error }}</div>
                            {% endfor %}
                        </div>
                        <button type="submit" class="btn btn-primary">Save Changes</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% block content %}
        {% csrf_token %}
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto custom-card">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <center>
                            <h1>Create your account</h1>
                            <hr>
                        </center>
                        <div class="form-group">
                            <label for="id_username">Username:</label>
                            <input type="text" class="form-control {% if form.username.errors %} is-invalid {% endif %}" id="id_username" name="username">
                            {% for error in form.username.errors %}
                                <div class="invalid-feedback">{{ error }}</div>
                            {% endfor %}
                        </div>
                        <div class="form-group">
                            <label for="id_email">Email:</label>
                            <input type="email" class="form-control {% if form.email.errors %} is-invalid {% endif %}" id="id_email" name="email">
                            {% for error in form.email.errors %}
                                <div class="invalid-feedback">{{ error }}</div>
                            {% endfor %}
                        </div>
                        <div class="form-group">
                            <label for="id_password1">Password:</label>
                            <input type="password" class="form-control {% if form.password1.errors %} is-invalid {% endif %}" id="id_password1" name="password1">
                            {% for error in form.password1.errors %}
                                <div class="invalid-feedback">{{ error }}</div>
                            {% endfor %}
                        </div>
                        <div class="form-group">
                            <label for="id_password2">Confirm Password:</label>
                            <input type="password" class="form-control {% if form.password2.errors %} is-invalid {% endif %}" id="id_password2" name="password2">
                            {% for error in form.password2.errors %}
                                <div class="invalid-feedback">{{ error }}</div>
                            {% endfor %}
                        </div>
                        <div class="form-group">
                            <label for="id_bio">Bio:</label>
                            <textarea class="form-control {% if form.bio.errors %} is-invalid {% endif %}" id="id_bio" name="bio"></textarea>
                            {% for error in form.bio.errors %}
                                <div class="invalid-feedback">{{ error }}</div>
                            {% endfor %}
                        </div>
                        <div class="form-group">
                            <label for="id_profile_picture">Profile Picture:</label>
                            <input type="file" class="form-control-file {% if form.profile_picture.errors %} is-invalid {% endif %}" id="id_profile_picture" name="profile_picture">
                            {% for error in form.profile_picture.errors %}
                                <div class="invalid-feedback">{{ error }}</div>
                            {% endfor %}
                        </div>
                        <button type="submit" class="btn btn-primary mt-3">Register</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{#        <div class="col-md-6">#}
{#            <div class="card-body">#}
{#                {% for field in form %}#}
{#                    {% for error in field.errors %}#}
{#                        <p class="text-danger">{{ error }}</p>#}
{#                    {% endfor %}#}
{#                {% endfor %}#}
{#            </div>#}
{#        </div>#}
{% endblock content %}